[libraries]

lib.files = [
"MaquinaEstados.vhd",
"SeguidorLinea_Brazo.vhd",
"LIDAR.vhd",
"kinematics.vhd",
"polarPWM.vhd",
"grab_ctrl.vhd",
"encoder_servo.vhd",
"Pruebas\\Motores\\TestMotores.vhd",
"_backups\\obsoletos\\tb_LIDAR_scan.vhd",
"_backups\\obsoletos\\LIDAR_Top.vhd",
"_backups\\obsoletos\\tb_polar_ik.vhd",
"_backups\\obsoletos\\tb_polar_kin.vhd",
"_backups\\obsoletos\\polar_ik.vhd",
"_backups\\obsoletos\\polar_kin.vhd",
"Brazo90Deg\\SeguidorLinea_Brazo_Servos90.vhd",
"Brazo90Deg\\polarPWM.vhd",
"Pruebas\\Brazo\\SeguidorLinea_BrazoTestBrazo.vhd",
"Pruebas\\Brazo\\tb_grab_ctrl.vhd",
"Pruebas\\Brazo\\tb_kinematics.vhd",
"Pruebas\\Sensor\\tb_VL53L0X.vhd",
"Pruebas\\Lidar\\LIDAR_Scan_Top.vhd",
"Pruebas\\Lidar\\LIDAR_Grab_Top.vhd",
"Pruebas\\Seguidor\\SeguidorLinea_Brazo_TestSeguidor.vhd",
"Pruebas\\Seguidor\\tb_MaquinaEstados.vhd",
"vl53l0x_pkg.vhd",
"VL53L0X.vhd",
]
